openapi: 3.1.0
info:
  title: public-http-api
  version: '1.0'
  summary: The Precog public HTTP REST API.
  description: The Precog public HTTP REST API.
  contact:
    url: 'https://precog.com'
    email: support@precog.com
servers:
  - url: 'http://localhost:30000'
security:
  - BearerAuth: []
paths:
  /sources:
    get:
      summary: Get Sources
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/connector-listing'
              examples:
                example-1:
                  value:
                    - id: '1'
                      kindId: '12'
                      name: 'Shop name: MyShop'
        '401':
          description: Unauthorized
      operationId: get-sources
      description: 'Retrieve the configured sources, optionally filtering by kind.'
      parameters:
        - schema:
            type: string
          in: query
          name: kind-id
    post:
      summary: Create Source
      tags: []
      operationId: post-sources
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connector-listing'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '422':
          description: Source kind unsupported or other semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '502':
          description: Problematic Request to External Server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Configure a new source.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/connector'
  '/sources/{source-id}/refresh':
    parameters:
      - schema:
          type: string
        name: source-id
        in: path
        required: true
    post:
      summary: Request source refresh
      tags: [ ]
      responses:
        '202':
          description: Accepted
        '401':
          description: Unauthorized
        '404':
          description: Source not found.
      operationId: refresh-source-by-id
      description: Refresh a particular source.
  '/sources/{source-id}':
    parameters:
      - schema:
          type: string
        name: source-id
        in: path
        required: true
    get:
      summary: Get a source
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connector'
              examples:
                example-1:
                  value:
                    config:
                      - name: Shop name
                        value: MyShop
                    id: '1'
                    kindId: '12'
                    name: 'Shop name: MyShop'
        '401':
          description: Unauthorized
        '404':
          description: Source not found.
      operationId: get-sources-source-id
      description: Get a particular source.
  '/sources/{source-id}/datasets':
    parameters:
      - schema:
          type: string
        name: source-id
        in: path
        required: true
    get:
      summary: Get datasets
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/dataset'
              examples:
                example-1:
                  value:
                    - id: '1'
                      name: Abandoned checkouts
                      sourceId: '1'
                    - id: '2'
                      name: Application charges
                      sourceId: '1'
                    - id: '3'
                      name: Application credits
                      sourceId: '1'
                    - id: '4'
                      name: Custom collections
                      sourceId: '1'
                    - id: '5'
                      name: Customer saved searches
                      sourceId: '1'
                    - id: '6'
                      name: Customers
                      sourceId: '1'
                    - id: '7'
                      name: Locations
                      sourceId: '1'
                    - id: '8'
                      name: Orders
                      sourceId: '1'
                    - id: '9'
                      name: Price rules
                      sourceId: '1'
                    - id: '10'
                      name: Products
                      sourceId: '1'
                    - id: '11'
                      name: Recurring application charges
                      sourceId: '1'
        '204':
          description: Dataset hasn't been discovered yet
        '401':
          description: Unauthorized
        '404':
          description: Source not found.
      operationId: get-sources-source-id-datasets
      description: Get all available datasets for the provided source.
  /destinations:
    get:
      summary: Get Destinations
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/connector-listing'
              examples:
                example-1:
                  value:
                    - id: '1'
                      kindId: '14'
                      name: 'Account: Precog, Database: Raw, Region: west-us-2.azure'
        '401':
          description: Unauthorized
      operationId: get-destinations
      description: 'Retrieve the configured destinations, optionally filtering by kind.'
      parameters:
        - schema:
            type: string
          in: query
          name: kind-id
    post:
      summary: Create Destination
      tags: []
      operationId: post-destinations
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connector-listing'
              examples:
                example-1:
                  value:
                    id: '1'
                    kindId: '14'
                    name: 'Account: Precog, Database: Raw, Region: west-us-2.azure'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '422':
          description: Destination kind unsupported or other semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Configure a new destination.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/connector'
  '/destinations/{destination-id}':
    parameters:
      - schema:
          type: string
        name: destination-id
        in: path
        required: true
    get:
      summary: Get a destination
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connector'
              examples:
                example-1:
                  value:
                    config: []
                    id: '1'
                    kindId: '14'
                    name: 'Account: Precog, Database: Raw, Region: west-us-2.azure'
        '401':
          description: Unauthorized
        '404':
          description: Destination not found.
      operationId: get-destinations-destination-id
      description: Get a particular destination.
  '/destinations/{destination-id}/configuration':
    parameters:
      - schema:
          type: string
        name: destination-id
        in: path
        required: true
    put:
      summary: Update a destination config
      tags: []
      operationId: put-destinations-destination-id
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '404':
          description: Destination not found.
        '422':
          description: Semantic Error
      description: Update a destination configuration for a particular destination .
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: '#/components/schemas/connector-config'
  '/kinds/{kind-id}':
    parameters:
      - schema:
          type: string
        name: kind-id
        in: path
        required: true
    get:
      summary: Get connector schema
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema:
                    $ref: '#/components/schemas/kind-schema'
                  auth:
                    $ref: '#/components/schemas/auth-schema-oauth2'
                required:
                  - schema
        '401':
          description: Unauthorized
        '404':
          description: Kind not found.
      operationId: get-kinds-kind-id
      description: Get the configuration schema for a particular kind of source.
  /kinds/source:
    get:
      summary: Get source kinds
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/connector-kind'
              examples:
                example-1:
                  value:
                    - id: '1'
                      name: Active Campaign
                    - id: '2'
                      name: Ariba Analytics
                    - id: '3'
                      name: Bing Ads
                    - id: '4'
                      name: Chargeback
                    - id: '5'
                      name: Clockify
                    - id: '6'
                      name: Everflow
                    - id: '7'
                      name: Facebook Ads
                    - id: '8'
                      name: Google Ads
                    - id: '9'
                      name: Gravity Forms
                    - id: '10'
                      name: Hubspot
                    - id: '11'
                      name: Salesforce
                    - id: '12'
                      name: Shopify
                    - id: '13'
                      name: WooCommerce
        '401':
          description: Unauthorized
      operationId: get-kinds-source
      description: Retrieve the available kinds of sources.
  /kinds/destination:
    get:
      summary: Get destination kinds
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/connector-kind'
              examples:
                example-1:
                  value:
                    - id: '14'
                      name: Snowflake
                    - id: '15'
                      name: Panoply
                    - id: '16'
                      name: Redshift
                    - id: '17'
                      name: Google BigQuery
                    - id: '18'
                      name: Firebolt
        '401':
          description: Unauthorized
      operationId: get-kinds-destination
      description: Retrieve the available kinds of destinations.
  /pipelines:
    get:
      summary: Get pipelines
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline-listing'
              examples:
                example-1:
                  value:
                    - id: '1'
                      name: Ecommerce
                    - id: '2'
                      name: Internal
                    - id: '3'
                      name: Staging environment
                    - id: '4'
                      name: Test environment
        '401':
          description: Unauthorized
      operationId: get-pipelines
      description: Get all pipelines.
    post:
      summary: Create pipeline
      tags: []
      operationId: post-pipelines
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/id'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Create a new pipeline.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pipeline'
        description: ''
  /pipelines/status:
    parameters: []
    get:
      summary: Get the pipeline status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline-status'
              examples:
                example-1:
                  value:
                    - pipelineId: '1'
                      status:
                        at: 1632428787341
                        state: loading
                    - pipelineId: '3'
                      status:
                        at: 1632128787341
                        state: succeeded
                    - pipelineId: '4'
                      status:
                        at: 1631251787341
                        state: failed
        '401':
          description: Unauthorized
      operationId: get-pipelines-status
      description: Get the status of all the pipelines.
  '/pipelines/{pipeline-id}':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    get:
      summary: Get a pipeline
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pipeline'
              examples:
                example-1:
                  value:
                    destinationId: '1'
                    id: '1'
                    name: Ecommerce
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found.
      operationId: get-pipelines-pipeline-id
      description: Get a particular pipeline.
  '/pipelines/{pipeline-id}/datasets':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    get:
      summary: Get the pipeline datasets
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/dataset'
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found.
      operationId: get-pipelines-pipeline-id-datasets
      description: Get the datasets in the provided pipeline.
    patch:
      summary: ''
      tags: []
      operationId: patch-pipelines-pipeline-id-datasets
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found. <or> Datasets not found.
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Add datasets to the provided pipeline.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dataset-update'
  '/pipelines/{pipeline-id}/details':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    get:
      summary: Get pipeline details
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pipeline-details'
              examples:
                example-1:
                  value:
                    datasets:
                      - dataset:
                          - id: '1'
                            name: Abandoned checkouts
                          - id: '2'
                            name: Application charges
                          - id: '3'
                            name: Application credits
                          - id: '4'
                            name: Custom collections
                          - id: '5'
                            name: Customer saved searches
                          - id: '6'
                            name: Customers
                          - id: '7'
                            name: Locations
                          - id: '8'
                            name: Orders
                          - id: '9'
                            name: Price rules
                          - id: '10'
                            name: Products
                          - id: '11'
                            name: Recurring application charges
                        source:
                          id: '1'
                          kind:
                            id: '12'
                            name: Shopify
                          name: 'Shop name: MyShop'
                    destination:
                      id: '1'
                      kind:
                        id: '14'
                        name: Snowflake
                      name: 'Account: Precog, Database: Raw, Region: west-us-2.azure'
                    pipeline:
                      id: '1'
                      name: Ecommerce
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found
      operationId: get-pipelines-pipeline-id-details
      description: Get all the details for the provided pipeline.
  '/pipelines/{pipeline-id}/status':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    get:
      summary: Get the pipeline datasets status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pipeline-dataset-status'
              examples:
                example-1:
                  value:
                    pipelineId: '1'
                    status:
                      state: succeeded
                      at: 0
                    datasets:
                      - id: string
                        outOfBand:
                          state: staging
                          at: 0
                        inBand:
                          state: staging
                          at: 0
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found
      operationId: get-pipelines-pipeline-id-status
      description: Get the status of the provided pipeline.
  '/pipelines/{pipeline-id}/loads':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    post:
      summary: Start a pipeline load
      tags: []
      operationId: post-pipelines-pipeline-id-loads
      responses:
        '202':
          description: Accepted - there are in-band datasets and a load has been scheduled to start
        '204':
          description: No Content - there are no in-band datasets
        '400':
          description: Bad Request - there are no datasets in pipeline
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found.
      description: Start a load for this pipeline.
  '/pipelines/{pipeline-id}/rename':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    put:
      summary: Rename a pipelne.
      tags: []
      operationId: put-pipelines-pipeline-id-rename
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Rename a pipeline.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pipeline-name'
  '/pipelines/{pipeline-id}/schedule':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    put:
      summary: Schedule a pipeline.
      tags: []
      operationId: put-pipelines-pipeline-id-schedule
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Schedule a pipeline.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pipeline-schedule'
        description: A list of cron expressions. An empty list means that the pipeline will not be loaded on a schedule.
    get:
      summary: Get the pipeline schedule
      tags: []
      operationId: get-pipelines-pipeline-id-schedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pipeline-schedule'
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found
      description: Get the pipeline schedule.
  '/pipelines/{pipeline-id}/notification':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    put:
      summary: Set email addresses to be notified on pipeline events.
      tags: []
      operationId: put-pipelines-pipeline-id-notification
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Set email addresses to be notified on pipeline events.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pipeline-notification'
        description: A list of email addresses. An empty list means that email notifications are disabled for the pipeline.
    get:
      summary: Get email addresses associated with the pipeline
      tags: []
      operationId: get-pipelines-pipeline-id-notification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pipeline-notification'
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found
      description: Get email addresses associated with the pipeline.
  '/pipelines/{pipeline-id}/loads/latest/logs':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    get:
      summary: Get pipeline logs for the latest load
      tags: []
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '204':
          description: This dataset has not yet been loaded
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found <OR> Dataset not found
      operationId: get-pipelines-pipeline-id-loads-latest-logs
      description: Get pipeline logs for the latest load and provided dataset
      parameters:
        - schema:
            type: string
          in: query
          name: dataset-id
          required: true
  /stripe/check:
    post:
      summary: Check Stripe subscription status
      tags: []
      operationId: post-stripe-check
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/url'
        '204':
          description: Valid Subscription
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '502':
          description: Problematic Request to External Server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                returnUrl:
                  type: string
                  minLength: 1
              required:
                - returnUrl
      description: Check the Stripe subscription status
  /stripe/session:
    post:
      summary: Create Stripe session
      tags: []
      operationId: post-stripe-session
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/url'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '404':
          description: Stripe customer not found
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '502':
          description: Problematic Request to External Server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                returnUrl:
                  type: string
                  minLength: 1
              required:
                - returnUrl
      description: Create a Stripe customer portal session
    parameters: []
components:
  schemas:
    connector:
      description: ''
      type: object
      title: ''
      properties:
        id:
          type: string
          minLength: 1
          readOnly: true
        kindId:
          type: string
          minLength: 1
        config:
          $ref: '#/components/schemas/connector-config'
        name:
          type: string
          minLength: 1
          readOnly: true
        auth:
          $ref: '#/components/schemas/auth-oauth2'
          writeOnly: true
      required:
        - id
        - kindId
        - config
        - name
    connector-listing:
      description: ''
      type: object
      title: ''
      properties:
        id:
          type: string
          minLength: 1
          readOnly: true
        kindId:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
      required:
        - id
        - kindId
        - name
    connector-config:
      description: ''
      type: array
      title: ''
      items:
        $ref: '#/components/schemas/connector-config-entry'
    kind-schema:
      description: ''
      type: array
      title: ''
      items:
        $ref: '#/components/schemas/kind-schema-entry'
    connector-kind:
      description: ''
      type: object
      title: ''
      properties:
        name:
          type: string
          minLength: 1
        id:
          type: string
          minLength: 1
      required:
        - name
        - id
    kind-schema-entry:
      description: ''
      type: object
      title: ''
      properties:
        description:
          type: string
        sensitive:
          type: boolean
        name:
          type: string
          minLength: 1
      required:
        - description
        - sensitive
        - name
    connector-config-entry:
      description: ''
      type: object
      properties:
        value:
          type: string
        name:
          type: string
          minLength: 1
      required:
        - value
        - name
    pipeline-listing:
      title: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
          readOnly: true
        name:
          type: string
          minLength: 1
      required:
        - id
        - name
    pipeline:
      title: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
          readOnly: true
        name:
          type: string
          minLength: 1
        destinationId:
          type: string
          minLength: 1
      required:
        - id
        - name
        - destinationId
    dataset:
      title: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        sourceId:
          type: string
          minLength: 1
      required:
        - id
        - name
        - sourceId
    id:
      title: ''
      type: object
      properties:
        id:
          type: string
      required:
        - id
    pipeline-name:
      title: ''
      type: object
      properties:
        name:
          type: string
          minLength: 1
      required:
        - name
    pipeline-schedule:
      title: ''
      type: object
      properties:
        schedule:
          type: array
          items:
            type: string
      required:
        - schedule
    pipeline-notification:
      title: ''
      type: object
      properties:
        emails:
          type: array
          items:
            type: string
      required:
        - emails
    pipeline-status:
      title: ''
      type: object
      properties:
        pipelineId:
          type: string
          minLength: 1
        status:
          $ref: '#/components/schemas/pipeline-load-state'
      required:
        - pipelineId
        - status
    dataset-status:
      title: ''
      type: object
      description: ''
      properties:
        id:
          type: string
          minLength: 1
        outOfBand:
          $ref: '#/components/schemas/outofband-state'
        inBand:
          $ref: '#/components/schemas/inband-state'
      required:
        - id
    pipeline-dataset-status:
      title: ''
      type: object
      properties:
        pipelineId:
          type: string
          minLength: 1
        status:
          $ref: '#/components/schemas/pipeline-load-state'
        datasets:
          type: array
          items:
            $ref: '#/components/schemas/dataset-status'
      required:
        - pipelineId
        - datasets
    pipeline-load-state:
      title: ''
      type: object
      properties:
        state:
          type: string
          enum:
            - succeeded
            - failed
            - loading
            - accepted
        at:
          type: number
      required:
        - state
        - at
    outofband-state:
      title: ''
      type: object
      properties:
        state:
          type: string
          enum:
            - accepted
            - staging
            - scheming
            - empty
            - failed
        at:
          type: number
      required:
        - state
        - at
    inband-state:
      title: ''
      type: object
      properties:
        state:
          type: string
          enum:
            - discovered
            - staging
            - writing
            - waiting
            - written
            - failed
        at:
          type: number
      required:
        - state
        - at
    pipeline-details:
      title: pipeline-details
      type: object
      properties:
        pipeline:
          required:
            - id
            - name
          type: object
          properties:
            id:
              type: string
              minLength: 1
            name:
              type: string
              minLength: 1
        destination:
          required:
            - id
            - name
            - kind
          type: object
          properties:
            id:
              type: string
              minLength: 1
            name:
              type: string
              minLength: 1
            kind:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: string
                  minLength: 1
                name:
                  type: string
                  minLength: 1
        datasets:
          type: array
          uniqueItems: true
          items:
            type: object
            properties:
              source:
                required:
                  - id
                  - name
                  - kind
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  kind:
                    type: object
                    required:
                      - id
                      - name
                    properties:
                      id:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
              dataset:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                  required:
                    - id
                    - name
            required:
              - source
              - dataset
        schedule:
          type: array
          uniqueItems: true
          items:
            type: string
            minLength: 1
        notifications:
          type: array
          uniqueItems: true
          items:
            type: string
            minLength: 1
      required:
        - pipeline
        - destination
        - datasets
        - schedule
        - notifications
    dataset-update:
      title: dataset-update
      type: object
      properties:
        action:
          type: string
          enum:
            - add
        datasetIds:
          type: array
          uniqueItems: true
          items:
            type: string
            minLength: 1
      required:
        - action
        - datasetIds
    error-message:
      title: error-message
      type: object
      properties:
        error:
          type: object
          required:
            - type
            - details
          properties:
            type:
              type: string
              minLength: 1
            details:
              type: string
      required:
        - error
    url:
      title: url
      type: object
      properties:
        url:
          type: string
          minLength: 1
      required:
        - url
    auth-schema-oauth2:
      title: auth-schema-oauth2
      type: object
      properties:
        type:
          type: string
          enum:
            - OAuth 2.0 code authorization
        details:
          type: object
          required:
            - uri
          properties:
            uri:
              type: string
              minLength: 1
      required:
        - type
        - details
    auth-oauth2:
      title: auth-oauth2
      type: object
      properties:
        type:
          type: string
          enum:
            - OAuth 2.0 code authorization
        details:
          type: object
          required:
            - authCode
            - redirectUri
          properties:
            authCode:
              type: string
              minLength: 1
            redirectUri:
              type: string
              minLength: 1
      required:
        - type
        - details
  responses: {}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
